//# sourceURL=J_ALTUI_loc_it.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home": "Casa",
	"Away":"Away",
	"Night":"Night",
	"Vacation":"Vacation",
	"Welcome to VERA Alternate UI": "Benvenuti a VERA UI Alternativo",
	"Room": "Stanze",
	"Rooms": "Stanze",
	"Device":"Device",
	"Devices": "Dispositivi",
	"Control Panel": "Pannello di Controllo",
	"Scenes": "Scena",
	"Scene Edit": "Scena Modificare",
	"Plugins": "Plugins",
	"Custom Pages": "Pagine Personalizzate",
	"Edit Pages": "Modifica Pagine",
	"Credits": "Crediti",
	"LuaTest": "LuaTesy",
	"LuaStart": "LuaInizio",
	"Optimize": "Ottimizza",
	"Editor": "Editore",
	"Close":"Close",
	"Custom Pages Editor": "Pagine Personalizzate Editore",
	"Lua Startup": "Lua Avviare",
	"Lua Code Test":"Lua Codice Verificare",
	"Options": "Options",
	"Unmuted,Muted":"Normale,Muto",
	"Normal,Debug":"Normale,Debug",
	"Up":"Alza",
	"Stop":"Fermare",
	"Down":"Giù",
	"Open":"Apri",
	"Unlock,Lock":"Sbloccare,Serratura",
	"Bypass,Arm":"Free,Armata",
	"Use Custom Pages":"Pagine Usare Personalizzate",
	"Edit Custom Pages":"Modifica di Pagine Personalizzate",
	"More":"Più",
	"Remote Access Login":"Accesso Remoto Log",
	"Reload Luup Engine":"Ricaricare Luup Motore",
	"Lua Startup Code":"Lua Codice Avviamento",
	"Lua Test Code":"Avvio Codice Lua",
	"Localization":"Localizzazione",
	"Misc":"Vario",
	"Create":"Crea",
	"Runs in all modes, or in selected mode": "Runs in all modes, or in selected mode",
	"Run" : "Eseguire",
	"OFF,ON":"Spento,Acceso",
	"Working":"Lavorare",
	"Holiday":"Vacanze",
	"Wind":"Vento",
	"Are you sure you want to delete scene ({0})":"xxx",
	"Controller {0} is busy, be patient.":"Controller {0} is busy, be patient.",
	"Submit":"Submit",
	"Save Changes":"Save Changes",
	"Trigger":"Trigger",
	"Triggers":"Triggers",
	"Timers":"Timers",
	"Actions":"Actions",
	"Lua":"Lua",
	"OffLabel":"OffLabel",
	"OnLabel":"OnLabel",
	"Label":"Label",
	"Min":"Min",
	"Green":"Green",
	"Orange":"Orange",
	"Red":"Red",
	"Max":"Max",
	"Ticks":"Ticks",
	"TimerName":"TimerName",
	"TimerType":"TimerType",
	"TimerInterval":"TimerInterval",
	"TimerDayOfWeek":"TimerDayOfWeek",
	"TimerDayOfMonth":"TimerDayOfMonth",
	"TriggerName":"TriggerName",
	"Delay":"Delay",
	"Action to switch OFF":"Action to switch OFF",
	"Action to switch ON":"Action to switch ON",
	"Action":"Action",
	"Device Variable Properties":"Device Variable Properties",
	"Parameters":"Parameters",
	"Value":"Value",
	"Variable":"Variable",
	"Attributes":"Attributes",
	"Load":"Load",
	"Info":"Info",
	"Image":"Image",
	"Run Scene":"Run Scene",
	"Edit":"xxx",
	"Camera":"xxx",
	"On Off":"xxx",
	"Gauge":"xxx",
	"Device Icon":"xxx",
	"Scene":"xxx",
	"Multi State":"xxx",
	"Mo":"xxx",
	"Tu":"xxx",
	"We":"xxx",
	"Th":"xxx",
	"Fr":"xxx",
	"Sa":"xxx",
	"Su":"xxx",
	"At a certain time of day":"xxx",
	"At sunrise":"xxx",
	"Before sunrise":"xxx",
	"After sunrise":"xxx",
	"At sunset":"xxx",
	"Before sunset":"xxx",
	"After sunset":"xxx",
	"Timer":"xxx",
	"**Illegal**":"xxx",
	"interval":"xxx",
	"day of week":"xxx",
	"day of month":"xxx",
	"absolute":"xxx",
	"Search":"xxx",
	"Remove":"xxx",
	"No Match":"xxx",
	"Reboot Vera":"xxx",
	"This plugin is a work in progress, it will continuously evolve over time.":"This plugin is a work in progress, it will continuously evolve over time.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>",
	"All":"xxx",
	"No Room":"xxx",
	"Device creation failed":"xxx",
	"Device {0} created successfully":"xxx {0} xxx",
	"Filter":"xxx",
	"Category":"xxx",
    "Could not create Room":"Could not create Room",
	"New Page":"New Page",
	"Page Properties":"Page Properties",
	"Delete this Page":"Delete this Page",
	"Save All Pages":"Save All Pages",
	"Files":"Fichiers",
	"Name":"Name",
	"Version":"Version",
	"Update":"Update",
	"Uninstall":"Uninstall",
	"Messages":"Messages",
	"zWave Network":"zWave Network",
	"ZWave":"ZWave",
	"Localize":"Localize",
	"Localizations":"Localizations",
	"Power Chart":"Power Chart",
	"Power":"Power",
	"Localization information":"Localization information",
	"Mesh":"Mesh",
	"Order By":"Order By",
	"Reset Poll Counters":"Reset Poll Counters",
	"Parent/Child Network":"Parent/Child Network","Parent/Child":"Parent/Child",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node"	,
	"Network Quality":"Network Quality",
	"Quality":"Quality",
	"Show":"Show",
	"ZWave Routes":"ZWave Routes",
	"Scene Action Group":"Scene Action Group",
  "Pause Scene":"Pause Scene",
	"Trigger Restriction":"Trigger Restriction",
	"Restrict trigger based on certain times":"Restrict trigger based on certain times",
	"Start Time":"Start Time",
	"Stop Time":"Stop Time",
	"zWave Routes":"zWave Routes",
	"zWaveRoutes":"zWaveRoutes",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"error happened during decoding triggers, probable duplicate ID or invalid format",
	"TblDevices":"TblDevices",
	"Table Devices":"Table Devices",
	"Update Neighbors":"Update Neighbors",
	"Update Neighbors succeeded":"Update Neighbors succeeded",
	"Copy to clipboard":"Copy to clipboard",
	"Data copied in clipboard":"Data copied in clipboard",
	"Code execution succeeded":"Code execution succeeded",
	"Code execution failed":"Code execution failed",
	"Reboot request succeeded":"Reboot request succeeded",
	"Reboot request failed":"Reboot request failed",
	"Favorite":"Favorite",
	"Favorites":"Favorites",
	"Variables":"Variables",
	"Used in":"Used in",
	"OsCommand":"OsCommand",
	"Disk Usage":"Disk Usage",
	"Free Space":"Free Space",
	"Plugin Files":"Plugin Files",
	"Log Sizes":"Log Sizes",
	"OS Command":"OS Command",
	"Frequent Commands":"Frequent Commands",
	"Output":"Output",
	"Os Command execution succeeded":"Os Command execution succeeded",
	"Version number or empty for latest official version":"Version number or empty for latest official version",
	"Update Plugin succeeded, be patient Luup will reload":"Update Plugin succeeded, be patient Luup will reload",
	"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below":"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below",
	"Os Command execution on vera failed.":"Os Command execution on vera failed.",
	"failed to execute":"failed to execute",
	"Are you Sure ?":"Are you Sure ?",
	"Yes":"Yes",
	"Are you sure you want to delete device ({0})":"Are you sure you want to delete device ({0})",
	"Are you sure you want to delete room":"Are you sure you want to delete room",
	"Are you sure you want to uninstall this plugin #{0} and all its created devices":"Are you sure you want to uninstall this plugin #{0} and all its created devices",
	"a newer version #{0} of ALTUI is available, do you want to upgrade ?":"a newer version #{0} of ALTUI is available, do you want to upgrade ?",
	"Question":"Question",
	"Options":"Options",
	"Show Video Thumbnail in Local mode":"Show Video Thumbnail in Local mode",
	"Cache Control":"Cache Control",
	"Custom Pages Control":"Custom Pages Control",
	"Refresh":"Refresh",
	"Search Logs":"Search Logs",
	"Tail Logs":"Tail Logs",
	"label":"label",
	"command":"command",
	"Add":"Add",
	"Default":"Default",
	"Command Parameters":"Command Parameters",
	"Parameter":"Parameter",
	"Test Code":"Test Code",
	"Panels":"Panels",
	"Reports":"Reports",
	"Evolutions":"Evolutions",
	"History":"History",
	"Date":"Date","Old":"Old","New":"New",
	"Scene History":"Scene History",
	"Button Label":"Button Label","Color":"Color",
	"Ran Scene #{0} successfully":"Ran Scene #{0} successfully",
	"Not used in scenes":"Not used in scenes",
	"Controller {0} did not respond":"Controller {0} did not respond",
	"Option":"Option",
	"Debug":"Debug",
	"All devices":"All devices",
	"One Device's States":"One Device's States",
	"Variable search":"Variable search",
	"Javascript code":"Javascript code",
	"Debug Tools":"Debug Tools",
	"Debug Actions":"Debug Actions",
	"Altui ID":"Altui ID",
	"Variable Name Pattern":"Variable Name Pattern",
	"an error happened during the execution":"an error happened during the execution",
	"Controller":"Controller",
	"Counters have been reset properly":"Counters have been reset properly",
	"do you want to change lua startup code ? if yes, it will generate a LUA reload, be patient...":"do you want to change lua startup code ? if yes, it will generate a LUA reload, be patient...",
	"Lua Startup code has been modified":"Lua Startup code has been modified",
	"Header":"Header",
	"Delay":"Delay",
	"Edited Scene {0} successfully ":"Edited Scene {0} successfully ",
	"Notification from {0}":"Notification from {0}",
	"Notify Users":"Notify Users",
	"Deleted Scene {0} successfully ":"Deleted Scene {0} successfully ",
	"Left Buttons are fixed on the page":"Left Buttons are fixed on the page",
	"See":"See"
	});
