//# sourceURL=J_ALTUI_loc_fr.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
  "Home":"Maison",
  "Away":"Distant",
  "Night":"Nuit",
  "Vacation":"Vacances",
  "Welcome to VERA Alternate UI": "Bienvenu dans AltUI pour VERA",
  "Rooms": "Pieces",
  "Device": "Périphérique",
  "Devices": "Périphériques",
  "Control Panel": "Controle",
  "Scenes": "Scènes",
  "Scene Edit": "Edition de Scene",
  "Plugins": "Plugins",
  "Custom Pages": "Pages Perso",
  "Edit Pages": "Pages Editeur",
  "Credits": "Crédits",
  "LuaTest": "LuaTest",
  "LuaStart": "LuaStart",
  "Optimize": "Optimise",
  "Editor": "Editor",
  "Close": "Fermer",
  "Custom Pages Editor": "Editeur de Pages",
  "LUA Startup": "LUA Startup",
  "LUA Code Test":"LUA Code Test",
  "Optimizations": "Optimisations",
  "Unmuted,Muted":"Normal,Mute",
  "Normal,Debug":"Normal,Debug",
  "Up":"Haut",
  "Stop":"Stop",
  "Down":"Bas",
  "Open":"Ouvrir",
  "Unlock,Lock":"Unlock,Lock",
  "Bypass,Arm":"Libre,Armé",
  "Use Custom Pages":"Utilise Pages",
  "Edit Custom Pages":"Edit Pages",
  "More":"Plus",
  "Remote Access Login":"Accès à Distance",
  "Reload Luup Engine":"Redémarrer Luup",
  "Lua Startup Code":"Démarrage Lua",
  "Lua Test Code":"Test Lua",
  "Localization":"Localisation",
  "Misc":"Divers",
  "Create":"Créer",
  "Runs in mode": "Exécute seulement en mode",
  "Run" : "Exécute",
  "OFF,ON":"OFF,ON",
  "Working":"Travail",
  "Holiday":"Vacances",
  "Wind":"Vent",
  "Are you sure you want to delete scene ({0})":"confirmez vous la destruction de la scene ({0})",
  "VERA did not respond":"VERA ne répond pas",
  "Submit":"Confirmer",
  "Save Changes":"Sauvegarder",
  "Trigger":"Evènement",
  "Triggers":"Evènements",
  "Timers":"Echéancier",
  "Actions":"Actions",
  "Lua":"Lua",
  "OffLabel":"Label Off",
  "OnLabel":"Label On",
  "Label":"Label",
  "Min":"Min",
  "Green":"Vert",
  "Orange":"Orange",
  "Red":"Rouge",
  "Max":"Max",
  "Ticks":"Traits",
  "TimerName":"Timer Nom",
  "TimerType":"Timer Type",
  "TimerInterval":"Timer Interval",
  "TimerDayOfWeek":"Timer Jour De Semaine",
  "TimerDayOfMonth":"Timer Jour Du Mois",
  "TriggerName":"Evènement Nom",
  "Delay":"Délai",
  "Action to switch OFF":"Action pour Eteindre",
  "Action to switch ON":"Action pour Allumer",
  "Action":"Action",
  "Device Variable Properties":"Propriétés du Périphérique",
  "Parameters":"Paramètres",
  "Value":"Valeur",
  "Variable":"Variable",
  "Attributes":"Attributs",
  "Load":"Charge",
  "Info":"Info",
  "Image":"Image",
  "Run Scene":"Exécute Scene",
  "Edit":"Edit",
  "Camera":"Caméra",
  "On Off":"On Off",
  "Gauge":"Jauge",
  "Device Icon":"Icone",
  "Scene":"Scène",
  "Multi State":"Multi Etats",
  "Mo":"Mo",
  "Tu":"Tu",
  "We":"We",
  "Th":"Th",
  "Fr":"Fr",
  "Sa":"Sa",
  "Su":"Su",
  "At a certain time of day":"A un moment de la journée",
  "At sunrise":"Au Lever du soleil",
  "Before sunrise":"Avant le Lever du soleil",
  "After sunrise":"Après le Lever du soleil",
  "At sunset":"Au Coucher du Soleil",
  "Before sunset":"Avant le Coucher du Soleil",
  "After sunset":"Après le Coucher du Soleil",
  "Timer":"Horloge",
  "**Illegal**":"**Illegal**",
  "interval":"intervalle",
  "day of week":"Jour de la Semaine",
  "day of month":"Jour du Mois",
  "absolute":"Heure Fixe",
  "Search":"Chercher",
  "Remove":"Effacer",
  "No Match":"Aucun",
  "Reboot Vera":"Redémarrer Vera",
  "This plugin is a work in progress, it will continuously evolves over time.":"Ce Plugin est un projet en cours, il continue d'évoluer au fil du temps.",
  "You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"Vous pouvez suivre les evolutions sur le <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a> Micasaverde",
  "All":"Tous",
  "No Room":"Pas de Pièce",
  "Device creation failed":"Echec de la creation du Périphérique",
  "Device {0} created successfully":"Périphérique {0} créé",
  "Filter":"Filtre",
  "Category":"Catégorie",
  "Could not create Room":"Echec de création de la pièce",
  "New Page":"Nouvelle Page",
  "Page Properties":"Propriétés",
  "Delete this Page":"Détruite cette page",
  "Save All Pages":"Sauver les pages",
  "Files":"Fichiers",
  "Name":"Nom",
  "Version":"Version",
  "Update":"Mise à jour",
  "Uninstall":"Désinstaller",
  "Messages":"Messages",
  "zWave Network":"Réseau zWave",
  "ZWave":"ZWave",
  "Localize":"Traduire",
  "Localizations":"Traductions",
  "Power Chart":"Graphique Puissance",
  "Power":"Puissance",
  "Localization information":"Information de Traduction",
  "Mesh":"Couverture",
  "Order By":"Trier par"
});
