//# sourceURL=J_ALTUI_loc_it.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home": "Casa",
	"Away":"Away",
	"Night":"Night",
	"Vacation":"Vacation",
	"Welcome to VERA Alternate UI": "Benvenuti a VERA UI Alternativo",
	"Rooms": "Stanze",
	"Device":"Device",
	"Devices": "Dispositivi",
	"Control Panel": "Pannello di Controllo",
	"Scenes": "Scena",
	"Scene Edit": "Scena Modificare",
	"Plugins": "Plugins",
	"Custom Pages": "Pagine Personalizzate",
	"Edit Pages": "Modifica Pagine",
	"Credits": "Crediti",
	"LuaTest": "LuaTesy",
	"LuaStart": "LuaInizio",
	"Optimize": "Ottimizza",
	"Editor": "Editore",
	"Close":"Close",
	"Custom Pages Editor": "Pagine Personalizzate Editore",
	"Lua Startup": "Lua Avviare",
	"Lua Code Test":"Lua Codice Verificare",
	"Optimizations": "Ottimizzazioni",
	"Unmuted,Muted":"Normale,Muto",
	"Normal,Debug":"Normale,Debug",
	"Up":"Alza",
	"Stop":"Fermare",
	"Down":"Giù",
	"Open":"Apri",
	"Unlock,Lock":"Sbloccare,Serratura",
	"Bypass,Arm":"Free,Armata",
	"Use Custom Pages":"Pagine Usare Personalizzate",
	"Edit Custom Pages":"Modifica di Pagine Personalizzate",
	"More":"Più",
	"Remote Access Login":"Accesso Remoto Log",
	"Reload Luup Engine":"Ricaricare Luup Motore",
	"Lua Startup Code":"Lua Codice Avviamento",
	"Lua Test Code":"Avvio Codice Lua",
	"Localization":"Localizzazione",
	"Misc":"Vario",
	"Create":"Crea",
	"Runs in all modes, or in selected mode": "Runs in all modes, or in selected mode",
	"Run" : "Eseguire",
	"OFF,ON":"Spento,Acceso",
	"Working":"Lavorare",
	"Holiday":"Vacanze",
	"Wind":"Vento",
	"Are you sure you want to delete scene ({0})":"xxx",
	"VERA is busy, be patient. (returned {0})":"VERA is busy, be patient. (returned {0})",
	"Submit":"Submit",
	"Save Changes":"Save Changes",
	"Trigger":"Trigger",
	"Triggers":"Triggers",
	"Timers":"Timers",
	"Actions":"Actions",
	"Lua":"Lua",
	"OffLabel":"OffLabel",
	"OnLabel":"OnLabel",
	"Label":"Label",
	"Min":"Min",
	"Green":"Green",
	"Orange":"Orange",
	"Red":"Red",
	"Max":"Max",
	"Ticks":"Ticks",
	"TimerName":"TimerName",
	"TimerType":"TimerType",
	"TimerInterval":"TimerInterval",
	"TimerDayOfWeek":"TimerDayOfWeek",
	"TimerDayOfMonth":"TimerDayOfMonth",
	"TriggerName":"TriggerName",
	"Delay":"Delay",
	"Action to switch OFF":"Action to switch OFF",
	"Action to switch ON":"Action to switch ON",
	"Action":"Action",
	"Device Variable Properties":"Device Variable Properties",
	"Parameters":"Parameters",
	"Value":"Value",
	"Variable":"Variable",
	"Attributes":"Attributes",
	"Load":"Load",
	"Info":"Info",
	"Image":"Image",
	"Run Scene":"Run Scene",
	"Edit":"xxx",
	"Camera":"xxx",
	"On Off":"xxx",
	"Gauge":"xxx",
	"Device Icon":"xxx",
	"Scene":"xxx",
	"Multi State":"xxx",
	"Mo":"xxx",
	"Tu":"xxx",
	"We":"xxx",
	"Th":"xxx",
	"Fr":"xxx",
	"Sa":"xxx",
	"Su":"xxx",
	"At a certain time of day":"xxx",
	"At sunrise":"xxx",
	"Before sunrise":"xxx",
	"After sunrise":"xxx",
	"At sunset":"xxx",
	"Before sunset":"xxx",
	"After sunset":"xxx",
	"Timer":"xxx",
	"**Illegal**":"xxx",
	"interval":"xxx",
	"day of week":"xxx",
	"day of month":"xxx",
	"absolute":"xxx",
	"Search":"xxx",
	"Remove":"xxx",
	"No Match":"xxx",
	"Reboot Vera":"xxx",
	"This plugin is a work in progress, it will continuously evolves over time.":"This plugin is a work in progress, it will continuously evolves over time.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>",
	"All":"xxx",
	"No Room":"xxx",
	"Device creation failed":"xxx",
	"Device {0} created successfully":"xxx {0} xxx",
	"Filter":"xxx",
	"Category":"xxx",
    "Could not create Room":"Could not create Room",
	"New Page":"New Page",
	"Page Properties":"Page Properties",
	"Delete this Page":"Delete this Page",
	"Save All Pages":"Save All Pages",
	"Files":"Fichiers",
	"Name":"Name",
	"Version":"Version",
	"Update":"Update",
	"Uninstall":"Uninstall",
	"Messages":"Messages",
	"zWave Network":"zWave Network",
	"ZWave":"ZWave",
	"Localize":"Localize",
	"Localizations":"Localizations",
	"Power Chart":"Power Chart",
	"Power":"Power",
	"Localization information":"Localization information",
	"Mesh":"Mesh",
	"Order By":"Order By",
	"Reset Poll Counters":"Reset Poll Counters",
	"Parent/Child Network":"Parent/Child Network","Parent/Child":"Parent/Child",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node"	,
	"Network Quality":"Network Quality",
	"Quality":"Quality",
	"Show":"Show",
	"ZWave Routes":"ZWave Routes",
	"Scene Action Group":"Scene Action Group",
  "Pause Scene":"Pause Scene",
	"Trigger Restriction":"Trigger Restriction",
	"Restrict trigger based on certain times":"Restrict trigger based on certain times",
	"Start Time":"Start Time",
	"Stop Time":"Stop Time",
	"zWave Routes":"zWave Routes",
	"zWaveRoutes":"zWaveRoutes",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"error happened during decoding triggers, probable duplicate ID or invalid format",
	"TblDevices":"TblDevices",
	"Table Devices":"Table Devices",
	"Update Neighbors":"Update Neighbors",
	"Update Neighbors succeeded":"Update Neighbors succeeded",
	"Copy to clipboard":"Copy to clipboard",
	"Data copied in clipboard":"Data copied in clipboard",
	"Code execution succeeded":"Code execution succeeded",
	"Code execution failed":"Code execution failed",
	"Reboot request succeeded":"Reboot request succeeded",
	"Reboot request failed":"Reboot request failed",
	"Favorite":"Favorite",
	"Favorites":"Favorites",
	"Variables":"Variables",
	"Used in":"Used in"
	});
