//# sourceURL=J_ALTUI_loc_fr.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home":"Maison",
	"Away":"Distant",
	"Night":"Nuit",
	"Vacation":"Vacances",
	"Welcome to VERA Alternate UI": "Bienvenue dans AltUI pour VERA",
	"Rooms": "Pièces",
	"Device": "Périphérique",
	"Devices": "Périphériques",
	"Control Panel": "Contrôle",
	"Scenes": "Scènes",
	"Scene Edit": "Édition de Scène",
	"Plugins": "Plugins",
	"Custom Pages": "Pages Perso",
	"Edit Pages": "Pages Éditeur",
	"Credits": "Crédits",
	"LuaTest": "LuaTest",
	"LuaStart": "LuaStart",
	"Optimize": "Optimise",
	"Editor": "Éditeur",
	"Close": "Fermer",
	"Custom Pages Editor": "Éditeur de Pages",
	"LUA Startup": "LUA Startup",
	"LUA Code Test":"LUA Code Test",
	"Options": "Options",
	"Unmuted,Muted":"Normal,Mute",
	"Normal,Debug":"Normal,Debug",
	"Up":"Haut",
	"Stop":"Stop",
	"Down":"Bas",
	"Open":"Ouvrir",
	"Unlock,Lock":"Unlock,Lock",
	"Bypass,Arm":"Libre,Armé",
	"Use Custom Pages":"Utilise Pages",
	"Edit Custom Pages":"Edit Pages",
	"More":"Plus",
	"Remote Access Login":"Accès à Distance",
	"Reload Luup Engine":"Redémarrer Luup",
	"Lua Startup Code":"Démarrage Lua",
	"Lua Test Code":"Test Lua",
	"Localization":"Localisation",
	"Misc":"Divers",
	"Create":"Créer",
	"Runs in all modes, or in selected mode": "Exécute dans tous les modes, ou seulement en mode(s)",
	"Run" : "Exécute",
	"OFF,ON":"OFF,ON",
	"Working":"Travail",
	"Holiday":"Vacances",
	"Wind":"Vent",
	"Are you sure you want to delete scene ({0})":"confirmez vous la destruction de la scène ({0})",
	"Controller {0} is busy, be patient.":"Le Controleur {0} est occupé, patience...",
	"Submit":"Confirmer",
	"Save Changes":"Sauvegarder",
	"Trigger":"Evènement",
	"Triggers":"Evènements",
	"Timers":"Echéancier",
	"Actions":"Actions",
	"Lua":"Lua",
	"OffLabel":"Label Off",
	"OnLabel":"Label On",
	"Label":"Label",
	"Min":"Min",
	"Green":"Vert",
	"Orange":"Orange",
	"Red":"Rouge",
	"Max":"Max",
	"Ticks":"Traits",
	"TimerName":"Timer Nom",
	"TimerType":"Timer Type",
	"TimerInterval":"Timer Interval",
	"TimerDayOfWeek":"Timer Jour De Semaine",
	"TimerDayOfMonth":"Timer Jour Du Mois",
	"TriggerName":"Evènement Nom",
	"Delay":"Délai",
	"Action to switch OFF":"Action pour Éteindre",
	"Action to switch ON":"Action pour Allumer",
	"Action":"Action",
	"Device Variable Properties":"Propriétés du Périphérique",
	"Parameters":"Paramètres",
	"Value":"Valeur",
	"Variable":"Variable",
	"Attributes":"Attributs",
	"Load":"Charge",
	"Info":"Info",
	"Image":"Image",
	"Run Scene":"Exécute Scène",
	"Edit":"Edit",
	"Camera":"Caméra",
	"On Off":"On Off",
	"Gauge":"Jauge",
	"Device Icon":"Icone",
	"Scene":"Scène",
	"Multi State":"Multi Etats",
	"Mo":"Lu",
	"Tu":"Ma",
	"We":"Me",
	"Th":"Je",
	"Fr":"Ve",
	"Sa":"Sa",
	"Su":"Di",
	"At a certain time of day":"A un moment de la journée",
	"At sunrise":"Au Lever du soleil",
	"Before sunrise":"Avant le Lever du soleil",
	"After sunrise":"Après le Lever du soleil",
	"At sunset":"Au Coucher du Soleil",
	"Before sunset":"Avant le Coucher du Soleil",
	"After sunset":"Après le Coucher du Soleil",
	"Timer":"Horloge",
	"**Illegal**":"**Illegal**",
	"interval":"intervalle",
	"day of week":"Jour de la Semaine",
	"day of month":"Jour du Mois",
	"absolute":"Heure Fixe",
	"Search":"Chercher",
	"Remove":"Effacer",
	"No Match":"Aucun",
	"Reboot Vera":"Redémarrer Vera",
	"This plugin is a work in progress, it will continuously evolve over time.":"Ce Plugin est un projet en cours, il continue d'évoluer au fil du temps.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"Vous pouvez suivre les évolutions sur le <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a> Micasaverde",
	"All":"Tous",
	"No Room":"Pas de Pièce",
	"Device creation failed":"Échec de la création du Périphérique",
	"Device {0} created successfully":"Périphérique {0} créé",
	"Filter":"Filtre",
	"Category":"Catégorie",
	"Could not create Room":"Échec de création de la pièce",
	"New Page":"Nouvelle Page",
	"Page Properties":"Propriétés",
	"Delete this Page":"Détruite cette page",
	"Save All Pages":"Sauver les pages",
	"Files":"Fichiers",
	"Name":"Nom",
	"Version":"Version",
	"Update":"Mise à jour",
	"Uninstall":"Désinstaller",
	"Messages":"Messages",
	"zWave Network":"Réseau zWave",
	"ZWave":"ZWave",
	"Localize":"Traduire",
	"Localizations":"Traductions",
	"Power Chart":"Graphique Puissance",
	"Power":"Puissance",
	"Localization information":"Information de Traduction",
	"Mesh":"Couverture",
	"Order By":"Trier par",
	"Reset Poll Counters":"Remise a Zéro des compteurs",
	"Parent/Child Network":"Réseau Parent/Enfant","Parent/Child":"Parent/Enfant",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Déplacer/Glisser pour rajouter ou enlever des contrôles. utiliser Ctrl+Click ou le lasso pour sélectionner plusieurs éléments",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Déplacer/Glisser pour fixer la position d'un nœud. Cliquer pour ouvrir ou refermer un nœud parent, Shift click pour libérer un nœud fixé",
	"Network Quality":"Qualité du Réseau",
	"Quality":"Qualité",
	"Show":"Voir",
	"ZWave Routes":"Routes ZWave",
	"Scene Action Group":"Groupe d'Action",
	"Pause Scene":"Pause Scene",
	"Trigger Restriction":"Evènement Limité",
	"Restrict trigger based on certain times":"Limite les Évènements à une certaine plage horaire",
	"Start Time":"Début",
	"Stop Time":"Fin",
	"zWave Routes":"Routes zWave ",
	"zWaveRoutes":"zWaveRoutes",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"une erreur est intervenue pendant l'affichage des Événements, probablement un ID en double ou un format invalide",
	"TblDevices":"TblDevices",
	"Table Devices":"Table Périphériques",
	"Update Neighbors":"Mise a jour des Voisins",
	"Update Neighbors succeeded":"Mise a jour des Voisins réussie",
	"Copy to clipboard":"Copier dans le clipboard",
	"Data copied in clipboard":"Données copiées dans le clipboard",
	"Code execution succeeded":"Exécution réussie",
	"Code execution failed":"Exécution avec erreur",
	"Reboot request succeeded":"Succès de la requête de Reboot",
	"Reboot request failed":"Echec de la requête de Reboot",
	"Favorite":"Favori",
	"Favorites":"Favoris",
	"Variables":"Variables",
	"Used in":"Utilisation",
	"OsCommand":"CommandeOS",
	"Disk Usage":"Utilisation Disque",
	"Free Space":"Espace(s) Libre",
	"Plugin Files":"Fichier des Plugins",
	"Log Sizes":"Taille des Logs",
	"OS Command":"Commande OS",
	"Frequent Commands":"Commandes Fréquentes",
	"Output":"Sortie",
	"Os Command execution succeeded":"L'exécution de la commande Os a réussie",
	"Version number or empty for latest official version":"Numéro de Version ou vide pour la dernière version officielle",
	"Update Plugin succeeded, be patient Luup will reload":"La mise a jour est demandée, Patience, Luup va redémarrer",
	"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below":"Tapez une commande Vera OS (Unix), la sortie stdout sera affichée ci dessous",
	"Os Command execution on vera failed.":"L'exécution de la commande OS a échoué.",
	"failed to execute":"Échec d'exécution",
	"Are you Sure ?":"Êtes vous certain ?",
	"Yes":"Oui",
	"Are you sure you want to delete device ({0})":"Voulez vous vraiment détruire le périphérique ({0})",
	"Are you sure you want to delete room":"Voulez vous vraiment détruire la pièce",
	"Are you sure you want to uninstall this plugin #{0} and all its created devices":"Voulez vous vraiment désinstaller ce plugin #{0} et tous les périphériques qu'il a créé",
	"a newer version #{0} of ALTUI is available, do you want to upgrade ?":"une nouvelle version #{0} de ALTUI est disponible, voulez vous mettre a jour ?",
	"Question":"Question",
	"Options":"Options",
	"Show Video Thumbnail in Local mode":"Vignettes Camera en Vidéo en mode local",
	"Cache Control":"Contrôle du Cache",
	"Custom Pages Control":"Contrôle des Pages Utilisateurs",
	"Refresh":"Rafraichir",
	"Search Logs":"Cherche Logs",
	"Tail Logs":"Fin Logs",
	"label":"label",
	"command":"commande",
	"Add":"Ajouter",
	"Default":"Défaut",
	"Command Parameters":"Paramètres de Commande",
	"Parameter":"Paramètre",
	"Test Code":"Test Code",
	"Panels":"Panneaux",
	"Reports":"Rapports",
	"Evolutions":"Évolutions",
	"History":"Historique",
	"Date":"Date","Old":"Ancien","New":"Nouveau",
	"Scene History":"Scene History",
	"Button Label":"Label Bouton","Color":"Couleur",
	"Ran Scene #{0} successfully":"Exécution avec succès de la Scène #{0}",
	"Not used in scenes":"Pas d'utilisation dans les scènes",
	"Controller {0} did not respond":"Le Contrôleur {0} ne répond pas"
});
