//# sourceURL=J_ALTUI_loc_it.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home": "Casa",
	"Away":"xxx",
	"Night":"xxx",
	"Vacation":"xxx",
	"Welcome to VERA Alternate UI": "Benvenuti a VERA UI Alternativo",
	"Rooms": "Stanze",
	"Device":"xxx",
	"Devices": "Dispositivi",
	"Control Panel": "Pannello di Controllo",
	"Scenes": "Scena",
	"Scene Edit": "Scena Modificare",
	"Plugins": "Plugins",
	"Custom Pages": "Pagine Personalizzate",
	"Edit Pages": "Modifica Pagine",
	"Credits": "Crediti",
	"LuaTest": "LuaTesy",
	"LuaStart": "LuaInizio",
	"Optimize": "Ottimizza",
	"Editor": "Editore",
	"Close":"xxx",
	"Custom Pages Editor": "Pagine Personalizzate Editore",
	"Lua Startup": "Lua Avviare",
	"Lua Code Test":"Lua Codice Verificare",
	"Optimizations": "Ottimizzazioni",
	"Unmuted,Muted":"Normale,Muto",
	"Normal,Debug":"Normale,Debug",
	"Up":"Alza",
	"Stop":"Fermare",
	"Down":"Giù",
	"Open":"Apri",
	"Unlock,Lock":"Sbloccare,Serratura",
	"Bypass,Arm":"Free,Armata",
	"Use Custom Pages":"Pagine Usare Personalizzate",
	"Edit Custom Pages":"Modifica di Pagine Personalizzate",
	"More":"Più",
	"Remote Access Login":"Accesso Remoto Log",
	"Reload Luup Engine":"Ricaricare Luup Motore",
	"Lua Startup Code":"Lua Codice Avviamento",
	"Lua Test Code":"Avvio Codice Lua",
	"Localization":"Localizzazione",
	"Misc":"Vario",
	"Create":"Crea",
	"Runs in mode": "Funziona in modalità",
	"Run" : "Eseguire",
	"OFF,ON":"Spento,Acceso",
	"Working":"Lavorare",
	"Holiday":"Vacanze",
	"Wind":"Vento",
	"Are you sure you want to delete scene ({0})":"xxx",
	"VERA did not respond":"xxx",
	"Submit":"xxx",
	"Save Changes":"xxx",
	"Trigger":"xxx",
	"Triggers":"xxx",
	"Timers":"xxx",
	"Actions":"xxx",
	"Lua":"xxx",
	"OffLabel":"xxx",
	"OnLabel":"xxx",
	"Label":"xxx",
	"Min":"xxx",
	"Green":"xxx",
	"Orange":"xxx",
	"Red":"xxx",
	"Max":"xxx",
	"Ticks":"xxx",
	"TimerName":"xxx",
	"TimerType":"xxx",
	"TimerInterval":"xxx",
	"TimerDayOfWeek":"xxx",
	"TimerDayOfMonth":"xxx",
	"TriggerName":"xxx",
	"Delay":"xxx",
	"Action to switch OFF":"xxx",
	"Action to switch ON":"xxx",
	"Action":"xxx",
	"Device Variable Properties":"xxx",
	"Parameters":"xxx",
	"Value":"xxx",
	"Variable":"xxx",
	"Attributes":"xxx",
	"Load":"xxx",
	"Info":"xxx",
	"Image":"xxx",
	"Run Scene":"xxx",
	"Edit":"xxx",
	"Camera":"xxx",
	"On Off":"xxx",
	"Gauge":"xxx",
	"Device Icon":"xxx",
	"Scene":"xxx",
	"Multi State":"xxx",
	"Mo":"xxx",
	"Tu":"xxx",
	"We":"xxx",
	"Th":"xxx",
	"Fr":"xxx",
	"Sa":"xxx",
	"Su":"xxx",
	"At a certain time of day":"xxx",
	"At sunrise":"xxx",
	"Before sunrise":"xxx",
	"After sunrise":"xxx",
	"At sunset":"xxx",
	"Before sunset":"xxx",
	"After sunset":"xxx",
	"Timer":"xxx",
	"**Illegal**":"xxx",
	"interval":"xxx",
	"day of week":"xxx",
	"day of month":"xxx",
	"absolute":"xxx",
	"Search":"xxx",
	"Remove":"xxx",
	"No Match":"xxx",
	"Reboot Vera":"xxx",
	"This plugin is a work in progress, it will continuously evolves over time.":"This plugin is a work in progress, it will continuously evolves over time.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>",
	"All":"xxx",
	"No Room":"xxx",
	"Device creation failed":"xxx",
	"Device {0} created successfully":"xxx {0} xxx",
	"Filter":"xxx",
	"Category":"xxx",
    "Could not create Room":"Could not create Room"

});
